name: Count pages and links
on:
  push:
    branches:
      - main

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Count pages and links
        run: python .github/scripts/count.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update statistics in README.md"
          file_pattern: "*.md"